apiVersion: batch/v1
kind: Job
metadata:
  name: kaniko
  labels:
    label: insert-labels-here
spec:
  backoffLimit: 1
  template:
    metadata:
      labels:
        label: insert-labels-here
    spec:
      nodeSelector:
        air-run-kaniko: Schedule
      serviceAccountName: air-run-sa
      containers:
        - name: kaniko-build
          image: gcr.io/kaniko-project/executor:v1.5.2
          imagePullPolicy: IfNotPresent
          args: [ "--dockerfile=/workspace/Dockerfile",
                  "--context=dir://context-dir",
                  "--destination=k8s-registry:80/image-name",
                  "--skip-tls-verify=true",
                  "--registry-certificate=k8s-registry=/certs/registry.crt",
                  "--cache=true",
                  "--cache-dir=/cache" ]
          volumeMounts:
            - name: workspace-storage
              mountPath: /workspace
            - name: certs-vol
              mountPath: /certs
            - name: kaniko-secret-vol
              mountPath: /kaniko/.docker
              readOnly: true
        - name: kaniko-poll
          image: alpine:3.13
          imagePullPolicy: IfNotPresent
          command: [ "/bin/sh" ]
          args:
            - /scripts/kaniko-poll.sh
          env:
            - name: JOB_NAME
              value: job-name-here
            - name: SERVICE_ACCOUNT_USERNAME
              valueFrom:
                secretKeyRef:
                  key: username
                  name: air-run-service-account-basic-auth
            - name: SERVICE_ACCOUNT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: air-run-service-account-basic-auth
          volumeMounts:
            - mountPath: /scripts
              name: scripts
            - name: kaniko-secret-vol
              mountPath: /kaniko/.docker
              readOnly: true
      restartPolicy: Never
      volumes:
        - name: scripts
          configMap:
            name: air-run-scripts-configmap
        - name: certs-vol
          hostPath:
            path: /data/kaniko/certs
            type: Directory
        - name: kaniko-secret-vol
          secret:
            secretName: kaniko-secret
        - name: "workspace-storage"
          persistentVolumeClaim:
            claimName: air-run-pv-claim
