apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "air-run-deploy.fullname" . }}
  labels:
    {{- include "air-run-deploy.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "air-run-deploy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "air-run-deploy.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "air-run-deploy.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /_health
          #     port: http
          #   initialDelaySeconds: 20
          # readinessProbe:
          #   httpGet:
          #     path: /_health
          #     port: http
          #   initialDelaySeconds: 20
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: "/app/uploads"
              name: {{ include "air-run-deploy.persistentVolumeStorageName" . }}
          env:          
            - name: "DATABASE_URL"
              valueFrom:
                secretKeyRef:
                  key: DATABASE_URL
                  name: {{ include "air-run-deploy.fullname" . }}
            - name: "SECRET_KEY_BASE"
              valueFrom:
                secretKeyRef:
                  key: SECRET_KEY_BASE
                  name: {{ include "air-run-deploy.fullname" . }}
            - name: "GUARDIAN_SECRET_KEY"
              valueFrom:
                secretKeyRef:
                  key: GUARDIAN_SECRET_KEY
                  name: {{ include "air-run-deploy.fullname" . }}
      volumes:
        - name: {{ include "air-run-deploy.persistentVolumeStorageName" . }}
          persistentVolumeClaim:
            claimName: {{ include "air-run-deploy.persistentVolumeClaimName" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
