apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "air-run-deploy.persistentVolumeName" . }}
  labels:
    {{- include "air-run-deploy.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.persistentVolume.storageClassName }}
  capacity:
    storage: {{ .Values.persistentVolume.storage }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/uploads"