apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "air-run-deploy.roleBindingName" . }}
  labels:
    {{- include "air-run-deploy.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "air-run-deploy.serviceAccountName" . }}
  namespace: default
roleRef:
  kind: Role
  name: {{ include "air-run-deploy.roleName" . }}
  apiGroup: rbac.authorization.k8s.io