apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "air-run-deploy.fullname" . }}
  labels:
    {{- include "air-run-deploy.labels" . | nindent 4 }}
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "create"]