apiVersion: v1
kind: ConfigMap
metadata:
  name: air-run-scripts-configmap
  labels:
    {{- include "air-run-deploy.labels" . | nindent 4 }}
data:
  {{- $files := .Files }}
  {{- range tuple "kaniko-poll.sh" "user-deployment-poll.sh" }}
  {{ . }}: |-
    {{- $files.Get . | nindent 4 }}
  {{- end }}