apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-name-here
  labels:
    label: insert-labels-here
spec:
  replicas: 1
  selector:
    matchLabels:
      label: insert-labels-here
  template:
    metadata:
      labels:
        label: insert-labels-here
    spec:
      serviceAccountName: air-run-sa
      containers:
        - name: deployment-main
          image: deployment-image-here
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
      imagePullSecrets:
        - name: regcred