apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-name-here
  labels:
    label: insert-labels-here
spec:
  replicas: 1
  selector:
    matchLabels:
      label: insert-labels-here
  template:
    metadata:
      labels:
        label: insert-labels-here
    spec:
      serviceAccountName: air-run-sa
      containers:
        - name: deployment-main
          image: deployment-image-here
          imagePullPolicy: Always
        - name: deployment-poll
          image: alpine:3.9
          imagePullPolicy: IfNotPresent
          command: [ "/bin/sh" ]
          args:
            - /scripts/user-deployment-poll.sh
          env:
            - name: DEPLOYMENT_NAME
              value: deployment-name-here
            - name: SERVICE_ACCOUNT_USERNAME
              valueFrom:
                secretKeyRef:
                  key: username
                  name: air-run-service-account-basic-auth
            - name: SERVICE_ACCOUNT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: air-run-service-account-basic-auth
          volumeMounts:
            - mountPath: /scripts
              name: scripts
      imagePullSecrets:
        - name: regcred
      volumes:
          - name: scripts
            configMap:
              name: air-run-scripts-configmap