apiVersion: batch/v1
kind: Job
metadata:
  name: kaniko
spec:
  backoffLimit: 1
  template:
    spec:
      containers:
      - name: kaniko
        image: gcr.io/kaniko-project/executor:latest
        args: ["--dockerfile=/workspace/Dockerfile",
                "--context=dir://context-dir",
                "--destination=k8s-registry:80/image-name",
                "--registry-mirror=k8s-registry:80",
                "--skip-tls-verify=true",
                "--registry-certificate=k8s-registry=/certs/registry.crt"]

        volumeMounts:
          - name: workspace-storage
            mountPath: /workspace
          - name: certs-vol
            mountPath: /certs
          - name: kaniko-secret-vol
            mountPath: /kaniko/.docker
            readOnly: true
      restartPolicy: Never
      volumes:
        - name: certs-vol
          hostPath:
            path: /opt/certs
            type: Directory
        - name: kaniko-secret-vol
          secret:
            secretName: kaniko-secret
        - name: "workspace-storage"
          persistentVolumeClaim:
            claimName: air-run-pv-claim
