apiVersion: v1
kind: Service
metadata:
  name: service-name-here
  labels:
    label: insert-labels-here
spec:
  selector:
    label: name
  ports:
    - protocol: "TCP"
      port: 6000
      targetPort: http
  type: NodePort