apiVersion: v1
kind: Service
metadata:
  name: tets-service
spec:
  selector:
    purpose: k8s-api-test
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
    nodePort: 30000
  type: NodePort