apiVersion: v1
kind: PersistentVolume
metadata:
  name: air-run-postgres
  labels:
    type: local
spec:
  capacity:
    storage: 9Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/postgres"